Apportionment Notes -*- mode: org -*-
#+STARTUP: showall latexpreview inlineimages

* Apportionment Definition
_apportionment_ - how to scale congress to population of states?
\[A_1 ... A_N\] - states
$N$ - number of states
$P_i$ - population of a state
$M$ - seats available in congress
$SD = \frac{P}{M}$ - standard divisor, people per seat
$q_i = \frac{P_i}{SD}$ - fair share of seats for state

_quota rule_ - every state should either get floor($q_i$) or ceil($q_i$)

* Apportionment methods
** Hamilton's Method
Give everyone the floor of their fair share.  Assign the remaining n seats to n states with highest remainder.
:example:
| State |     A |      B |    C |     D |    E |     F |   sum |
|-------+-------+--------+------+-------+------+-------+-------|
| $P_i$ |  1646 |   6936 |  154 |  2091 |  685 |   988 | 12500 |
| $q_i$ | 32.92 | 138.71 | 3.08 | 41.82 | 13.7 | 19.76 |   250 |
| floor |    32 |    138 |    3 |    41 |   13 |    19 |   246 |

So remaining for seats are assigned to A,B,D,F
:END:
** Adam's Method
Modify $SD$ until the sum of the ceils of fair shares of seats is equal to the total seats available

$\sum \lceil(q_i)\rceil = \sum \frac{P_i}{SD} \geq M$

so $SD$ needs to be increased until

$\sum \lceil(q_i)\rceil = \sum \frac{P_i}{SD} = M$

*its possible to violate the quote rule*

** Webster's Method
Same as Adam's method, but using rounding.

$\sum \lceil(q_i)\rceil = \sum \frac{P_i}{SD} \approx M$

so increase or decrease $SD$ until 

$\sum \lceil(q_i)\rceil = \sum \frac{P_i}{SD} = M$
** Hunting-Hill Method
This method is currently in use today.

Find the geometric mean of the ceiling and floor of the the fair shares for each state.
If the fair share is greater than the geometric mean, use the ceiling.
If the fair share is less than the geometric mean, use the floor.

If $q_i \geq \sqrt{floor(q_i)ceil(q_i)}$, use $ceil(q_i)$
If $q_i \leq \sqrt{floor(q_i)ceil(q_i)}$, use $floor(q_i)$
